name: CI
on: [push]

jobs:
  main:
    runs-on: nix
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Files
        run: |
          echo ${{ gitea.workspace }}
          ls ${{ gitea.workspace }}
      - name: Fmt
        run: |
          nix fmt
          git diff --exit-code
      - name: Build
        shell: nix develop '.#ci' --command bash -eo pipefail {0}
        run: |
          cachix use jvgpkgs
          nix build '.#packages.x86_64-linux.all'
      - name: Push
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        shell: nix develop '.#ci' --command bash -eo pipefail {0}
        run: |
          push-cachix
